package component:usb@0.1.0;

interface descriptors {
    use types.{direction, sync-type, transfer-type, usage-type, version};

    record endpoint-descriptor {
        address: u8,
        direction: direction,
        interval: u8,
        max-packet-size: u16,
        number: u8,
        refresh: u8, // Audio
        sync-type: sync-type,
        synch-address: u8, // Audio
        transfer-type: transfer-type,
        usage-type: usage-type
    }

    record interface-descriptor {
        number: u8,
        alternate-setting: u8,
        class-code: u8,
        subclass-code: u8,
        protocol: u8,
        interface-string-index: u8,
        endpoint-descriptors: list<endpoint-descriptor>
    }

    record configuration-descriptor {
        name: option<string>,
        max-power: u16,
        number: u8,
        interfaces: list<interface-descriptor>
    }

    record device-descriptor {
        device-class: u8,
        device-protocol: u8,
        device-subclass: u8,
        device-version: version,
        product-id: u16,
        usb-version: version,
        vendor-id: u16,
        max-packet-size: u8,
        manufacturer-string-index: option<u8>,
        product-string-index: option<u8>,
        serial-number-string-index: option<u8>,
        num-configurations: u8
    }
}
