package component:usb@0.1.0;

interface types {

    enum device-handle-error {
        io,
        invalid-param,
        access,
        no-device,
        not-found,
        busy,
        timeout,
        overflow,
        pipe,
        interrupted,
        no-mem,
        not-supported,
        bad-descriptor,
        other
    }

    enum direction { in, out }

    enum usage-type { data, feedback, feedback-data, reserved }

    enum sync-type { no-sync, asynchronous, adaptive, synchronous }

    enum transfer-type { control, isochronous, bulk, interrupt }

    record version {
        major: u8,
        minor: u8,
        subminor: u8
    }
}
